addons:
    apt:
        packages:
        - mailutils
dist: bionic

env:
  global:
    - secure: p5CUXtK2h5N1Or2gXt6L6cbXA7D153kZVAghxURv66fxEbDOmb5tV9Oo+Bled18uLaigft6spQXVtQDm64QfhFhMfc2KBzAgrF08Czjq9Lxgdrkb/j9/oTYUMC6lo9WML8UzMWeveEBFySlZA+AjXCcTfj51Pu6L4kd5lP1F9RII6xL89yYQ4uWaufrKYptfLtdNQ7gOy+XQ49vSXRjKxgYIFJhs/2dxk/HeZ0vnCciaWcCeSHtDWJzxSjJ0hLJB2ow/8TLsDp60SnZmggLRg/rNXwDUM8jpcN69m7aOtGYd0tIF7xTFIwqieaUAEg88ryzlpoo7heM4hH8gGKIbLAXshtxFzRefCVhmWQ7r15YQ5icn8FOkhmE859bymjEJlWHWzQeOGit64viCtmqBGdA2+UJVzYGs5u43JS6Q0eZsnA7OmXNc45O5co9qRoCRgqhuNLTyhds2homb0EbgGRtkE9kLid0Ms1Zcc+yUVQmDTWAeShq0nvnjYZY7bGG0TwBfNNd8zIApgOe/kct1SdYpifFMJGaWkvd30vyVifD/8eOeatmjqRtUOZXT+97B8+wrhF53+CzRhN800lhII7gULVpmIKAhFQyYGm6kl8ZN5I2qanek0ZSjB9Yq+5IzAcU7xG+ipU3AY84V+cp/vlXx+MspJcjw4t8ukJqvOLk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/nginx-ultimate-bad-bot-blocker
    - GIT_BRANCH: master

matrix:
  fast_finish: true

before_install:
  - export TZ=Africa/Johannesburg

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --assume-yes nginx-extras
  - sudo apt-get -y install dos2unix

script:
  # GENERATE BLOCKER FILES
  - bash .dev-tools/generate-files.sh
  # THE NEWLY GENERATED BLOCKER FILES
  - bash .dev-tools/install-nginx-1.sh
  - bash .dev-tools/test-blocker-false-positives.sh
  - bash .dev-tools/test-blocker-quick.sh
  - bash .dev-tools/test-blocker-badwords.sh
  - bash .dev-tools/test-blocker-whitelist-domains.sh
  - bash .dev-tools/test-blocker-whitelist-ips.sh
  - bash .dev-tools/test-blocker-rate-limiting.sh
  - bash .dev-tools/test-blocker-whitelist.sh
  # TEST install-ngxblocker update-ngxblocker and setup-ngxblocker
  - bash .dev-tools/install-nginx-2.sh
  - bash .dev-tools/test-nginx-2.sh
  - bash .dev-tools/install-nginx-3.sh
  - bash .dev-tools/test-nginx-3.sh
  - bash .dev-tools/test-setupngxblocker.sh
  # TEST ANY NEW CHANGES TO THE BLOCKER
  - bash .dev-tools/install-nginx-1.sh
  - bash .dev-tools/beta-install-nginx-testing-of-changes.sh
  - bash .dev-tools/beta-test-blocker-false-positives.sh
  - bash .dev-tools/beta-test-blocker.sh
  - bash .dev-tools/beta-test-blocker-badwords.sh
  - bash .dev-tools/beta-test-blocker-whitelist-domains.sh
  - bash .dev-tools/beta-test-blocker-whitelist-ips.sh
  - bash .dev-tools/beta-test-blocker-rate-limiting.sh
  - bash .dev-tools/beta-test-blocker-whitelist.sh
  # TEST NGINX MAINLINE
  - bash .dev-tools/install-nginx-mainline-ppa.sh
  - bash .dev-tools/test-nginx-mainline-ppa.sh
  - bash .dev-tools/install-nginx-mainline-nginx.sh
  - bash .dev-tools/test-nginx-mainline-nginx.sh
  # IF ALL TESTS PASSED - COMMIT AND DEPLOY BUILD
  - bash .dev-tools/modify-files-and-commit.sh

before_deploy:
  - bash .dev-tools/deploy-package.sh

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
      - .latest_release/conf.d.tar.gz
      - .latest_release/bots.d.tar.gz
  skip_cleanup: true
  on:
    repo: mitchellkrogza/nginx-ultimate-bad-bot-blocker
    tags: false
    branches:
      except:
        - "/^v[0-9]/"
        - "/^V.*$/"
    branches:
       only:
         - "master"
notifications:
  on_success: change
  on_failure: always
